export const dataDemo = [
  {
    key: '1',
    FullName: 'Huynh Nhat Hao',
    Email: 'haohn19411c@st.uel.edu.vn',
    Department: 'Hoc Thuat',
    Position: 'Thanh vien',
  },
  {
    key: '1',
    FullName: 'Huynh Nhat Hao',
    Email: 'haohn19411c@st.uel.edu.vn',
    Department: 'Hoc Thuat',
    Position: 'Thanh vien',
  },
  {
    key: '1',
    FullName: 'Huynh Nhat Hao',
    Email: 'haohn19411c@st.uel.edu.vn',
    Department: 'Hoc Thuat',
    Position: 'Thanh vien',
  },
  {
    key: '1',
    FullName: 'Huynh Nhat Hao',
    Email: 'haohn19411c@st.uel.edu.vn',
    Department: 'Hoc Thuat',
    Position: 'Thanh vien',
  },
  {
    key: '1',
    FullName: 'Huynh Nhat Hao',
    Email: 'haohn19411c@st.uel.edu.vn',
    Department: 'Hoc Thuat',
    Position: 'Thanh vien',
  },
  {
    key: '1',
    FullName: 'Huynh Nhat Hao',
    Email: 'haohn19411c@st.uel.edu.vn',
    Department: 'Hoc Thuat',
    Position: 'Thanh vien',
  },
  {
    key: '1',
    FullName: 'Huynh Nhat Hao',
    Email: 'haohn19411c@st.uel.edu.vn',
    Department: 'Hoc Thuat',
    Position: 'Thanh vien',
  },
  {
    key: '1',
    FullName: 'Huynh Nhat Hao',
    Email: 'haohn19411c@st.uel.edu.vn',
    Department: 'Hoc Thuat',
    Position: 'Thanh vien',
  },
  {
    key: '1',
    FullName: 'Huynh Nhat Hao',
    Email: 'haohn19411c@st.uel.edu.vn',
    Department: 'Hoc Thuat',
    Position: 'Thanh vien',
  },
];
